### ISSUE TITLE
Questions for multi-GPU prompt tuning

### ISSUE THREAD

**Issue by Chengzhe-Feng** [adf1178/PT4Code#10]
I try to reproduce the code-summarization task with the instruction：
`python prompt_t5.py --visible_gpu "0,1,2,3" --lang java --train_batch_size 32 --eval_batch_size 16 --max_source_length 256 --max_target_length 128 --log_name=./log/java.log --do_train --do_eval` 
I only change your instruction and all code files remain unchanged.
But unfortunately, I faced a problem that  console threw this error :

Traceback (most recent call last):
  File "prompt_t5.py", line 538, in <module>
    main(my_args)
  File "prompt_t5.py", line 286, in main
    loss = model(batch)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 449, in forward
    return self._forward(*args, **kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 465, in _forward
    outputs = self.prompt_model(batch)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/openprompt/pipeline_base.py", line 210, in forward
    batch = self.template.process_batch(batch)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/openprompt/prompts/soft_template.py", line 94, in process_batch
    inputs_embeds = self.raw_embedding(batch['input_ids'])
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/home/anaconda3/envs/lmass/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not tuple

Do you have any idea what may trigger this error?

**Comment by adf1178** [comment]
I have never met this error, but you can check the input type of the embedding layer or 'use a single gpu'. Maybe it is caused by the bug in openprompt about multiple GPUs.

**Comment by Chengzhe-Feng** [comment]
Single GPU tuning was fine.  Could you please provide the version of Openprompt in your environment？ Thx.

**Comment by adf1178** [comment]
I run these experiments about one year ago, I forgot the detailed version but it was about 0.1.2

**Comment by Chengzhe-Feng** [comment]
I have tried a few ways to solve this problem：
1.  Modify Openprompt to convert variables to tensor, like
`raw_embeds = self.raw_embedding(batch['input_ids'])
    if isinstance(raw_embeds, tuple):
        # concatenate the tensors in the tuple
        inputs_embeds = torch.cat(raw_embeds, dim=-1)
    else:
        inputs_embeds = raw_embeds`
2. Changing the version of Pytorch or Openprompt

But sadly they all failed and triggered the error above.

Could you please provide the environment that can tune the model in a multi-GPU way?  A `requirement.txt` would be of great help.
And by the way, You tune your model in a multi-GPU way by torch.DataParallel or torch.DistributedDataParallel? It seems that Openprompt does not support DistributedDataParallel.
THX!

**Comment by adf1178** [comment]
I really appreciate your great effort in our work. In fact, I need to do multiple experiments at once so I never tuned the model in multi GPUs :(  If you really want to tune the model in multi gpus, you may use another implementation  **prefix tuning** https://github.com/XiangLi1999/PrefixTuning.

**Comment by Chengzhe-Feng** [comment]
Thx for your help. In fact, I insist on using multiple cards because of the lack of memory on a single card. 
While reducing batch_size to tune your model with 12G memory, the performance of the summarization task drops dramatically. So I choose to use multi-GPU to solve it. 
After several failed attempts to modify Openprompt, maybe I should just use mix-precision to reproduce the summarization task with a single GPU. XD
